<?php
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<?php echo $this->getChildHtml('import_status'); ?>
<?php echo $this->getChildHtml('import_status_summary'); ?>

<div id="report-container"></div>
